# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Petros Kalogiannakis
firstname: Petros
lastname: Kalogiannakis
alias: kalpetros
email: email [at] petroskal.com
emailAlt: kalpetros [at] gmail.com
emailAlt2: kalpetros [at] protonmail.com
emailKey: "0xAEA16D60"
description: > # this means to ignore newlines until "baseurl:"
  Full Stack Web Developer
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.petroskal.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
